### ISSUE TITLE
Include locations

### ISSUE THREAD

**Issue by horjecazador** [horjecazador/D4#8]
Includes shouldn't be in .h files unless they're used in the .h file itself.

**Comment by acuratang** [comment]
It is used in the header, and the function disruptions are in the .cpp file
2016/2/28 下午11:34於 "horjecazador" <notifications@github.com>寫道：

**Comment by horjecazador** [comment]
In tracker.h none of the includes are used, except for string and wherever the Mat type is derived from.

**Comment by bmhuggett** [comment]
Is this dealt with?
